# Generated by Django 6.0.3 on 2026-04-06 13:42

import shipping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(default=shipping.models.generate_tracking_id, max_length=50, unique=True),
        ),
    ]
