# Generated by Django 6.0.3 on 2026-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('service_enquiry', models.CharField(choices=[('International Express', 'International Express'), ('Ocean Freight', 'Ocean Freight'), ('Road Freight', 'Road Freight'), ('Warehousing & Fulfillment', 'Warehousing & Fulfillment'), ('Customs Clearance', 'Customs Clearance'), ('General Enquiry', 'General Enquiry'), ('Track a Shipment', 'Track a Shipment')], max_length=50)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
